/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    LoginComponent: typeof import('./components/MainView/LoginComponent.vue')['default']
    MainComponent: typeof import('./components/MainView/MainComponent.vue')['default']
    MensageEmailComponent: typeof import('./components/MainView/MensageEmailComponent.vue')['default']
    RecoveryComponent: typeof import('./components/MainView/RecoveryComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
